package movie.bw.com.svntext.dao;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import movie.bw.com.svntext.ResultBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "RESULT_BEAN".
*/
public class ResultBeanDao extends AbstractDao<ResultBean, Integer> {

    public static final String TABLENAME = "RESULT_BEAN";

    /**
     * Properties of entity ResultBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property MovieId = new Property(0, int.class, "movieId", true, "MOVIE_ID");
        public final static Property Director = new Property(1, String.class, "director", false, "DIRECTOR");
        public final static Property HorizontalImage = new Property(2, String.class, "horizontalImage", false, "HORIZONTAL_IMAGE");
        public final static Property ImageUrl = new Property(3, String.class, "imageUrl", false, "IMAGE_URL");
        public final static Property Name = new Property(4, String.class, "name", false, "NAME");
        public final static Property Score = new Property(5, double.class, "score", false, "SCORE");
        public final static Property Starring = new Property(6, String.class, "starring", false, "STARRING");
    }

    private Query<ResultBean> bean_ResultQuery;

    public ResultBeanDao(DaoConfig config) {
        super(config);
    }
    
    public ResultBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"RESULT_BEAN\" (" + //
                "\"MOVIE_ID\" INTEGER PRIMARY KEY NOT NULL ," + // 0: movieId
                "\"DIRECTOR\" TEXT," + // 1: director
                "\"HORIZONTAL_IMAGE\" TEXT," + // 2: horizontalImage
                "\"IMAGE_URL\" TEXT," + // 3: imageUrl
                "\"NAME\" TEXT," + // 4: name
                "\"SCORE\" REAL NOT NULL ," + // 5: score
                "\"STARRING\" TEXT);"); // 6: starring
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"RESULT_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ResultBean entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getMovieId());
 
        String director = entity.getDirector();
        if (director != null) {
            stmt.bindString(2, director);
        }
 
        String horizontalImage = entity.getHorizontalImage();
        if (horizontalImage != null) {
            stmt.bindString(3, horizontalImage);
        }
 
        String imageUrl = entity.getImageUrl();
        if (imageUrl != null) {
            stmt.bindString(4, imageUrl);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(5, name);
        }
        stmt.bindDouble(6, entity.getScore());
 
        String starring = entity.getStarring();
        if (starring != null) {
            stmt.bindString(7, starring);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ResultBean entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getMovieId());
 
        String director = entity.getDirector();
        if (director != null) {
            stmt.bindString(2, director);
        }
 
        String horizontalImage = entity.getHorizontalImage();
        if (horizontalImage != null) {
            stmt.bindString(3, horizontalImage);
        }
 
        String imageUrl = entity.getImageUrl();
        if (imageUrl != null) {
            stmt.bindString(4, imageUrl);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(5, name);
        }
        stmt.bindDouble(6, entity.getScore());
 
        String starring = entity.getStarring();
        if (starring != null) {
            stmt.bindString(7, starring);
        }
    }

    @Override
    public Integer readKey(Cursor cursor, int offset) {
        return cursor.getInt(offset + 0);
    }    

    @Override
    public ResultBean readEntity(Cursor cursor, int offset) {
        ResultBean entity = new ResultBean( //
            cursor.getInt(offset + 0), // movieId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // director
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // horizontalImage
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // imageUrl
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // name
            cursor.getDouble(offset + 5), // score
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6) // starring
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ResultBean entity, int offset) {
        entity.setMovieId(cursor.getInt(offset + 0));
        entity.setDirector(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setHorizontalImage(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setImageUrl(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setScore(cursor.getDouble(offset + 5));
        entity.setStarring(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
     }
    
    @Override
    protected final Integer updateKeyAfterInsert(ResultBean entity, long rowId) {
        return entity.getMovieId();
    }
    
    @Override
    public Integer getKey(ResultBean entity) {
        if(entity != null) {
            return entity.getMovieId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ResultBean entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "result" to-many relationship of Bean. */
    public List<ResultBean> _queryBean_Result(String name) {
        synchronized (this) {
            if (bean_ResultQuery == null) {
                QueryBuilder<ResultBean> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Name.eq(null));
                bean_ResultQuery = queryBuilder.build();
            }
        }
        Query<ResultBean> query = bean_ResultQuery.forCurrentThread();
        query.setParameter(0, name);
        return query.list();
    }

}
